name: Continuos Integration
on: 
  push:
    branches:
      - github-actions
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Print Hello
        run: echo "Github Actions is working!"
    