name: Run Tests

on:
  push:
    branches:
      - docker-build
    paths:
      - .github/workflows/04-tests.yml
  workflow_dispatch:
    
jobs:
  ci:
    name: validate ${{matrix.service}}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        service:
          - gateway
          - auth-service 
          - employee-service 
          - admin-service 
          - dashboard-service 


    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
          cache-dependency-path: ${{ matrix.service }}/requirements-dev.txt
      - name: check python version 
        run: |
         python --version
         pip --version

      - name: upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install Dependencies 
        run: pip install -r ${{matrix.service}}/requirements-dev.txt
        
      - name: Run isort
        working-directory: ${{ matrix.service }}
        run: |
          isort --check-only .

      - name: Show Black Version
        working-directory: ${{ matrix.service }}
        run: |
          black --version

      - name: Check code formatting
        working-directory: ${{matrix.service}}
        run: |
          black --check .

      - name: Run flake8
        working-directory: ${{matrix.service}}
        run: |
          flake8 .

      - name: Run Bandit
        run: |
          bandit \
            -c .bandit \
            -r ${{ matrix.service }} \
            -f json \
            -o bandit-report.json


      - name: Upload Bandit Report
        uses: actions/upload-artifact@v4
        with:
          name: bandit-${{ matrix.service }}
          path: bandit-report.json


      - name: Create .env
        run: |
          cat > .env <<EOF
          POSTGRES_USER=${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB=${{ secrets.POSTGRES_DB }}
          POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}

          DATABASE_URL=${{ secrets.DATABASE_URL }}

          AUTH_SERVICE_URL=${{ secrets.AUTH_SERVICE_URL }}
          EMPLOYEE_SERVICE_URL=http://employee-service:5002
          ADMIN_SERVICE_URL=http://admin-service:5003
          DASHBOARD_SERVICE_URL=http://dashboard-service:5004

          JWT_SECRET=${{ secrets.JWT_SECRET }}
          JWT_ALGO=HS256
          JWT_EXPIRES_MIN=120
          FLASK_DEBUG=False
          EOF


      - name: Start PostgreSQL
        run: |
          docker compose up -d postgres

      - name: Wait for PostgreSQL
        run: |
          until [ "$(docker inspect -f '{{.State.Health.Status}}' ems-postgres)" = "healthy" ]; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done



      - name: Start Auth Service
        run: |
          docker compose up -d auth-service


      - name: Wait for Auth Service
        run: sleep 10


      - name: Run Pytest
        working-directory: ${{ matrix.service }}
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_ALGO: HS256
          JWT_EXPIRES_MIN: 120
          FLASK_DEBUG: "False"
        run: |
          python -m pytest -v


      - name: Stop Docker Compose
        if: always()
        run: |
          docker compose down -v


      - name: CI Completed
        run: echo "${{matrix.service}} installed and code quality and security checks Completed successfully!!"
