name: Docker Build

on:
  push:
    branches:
      - docker-build
  workflow_dispatch:


jobs:
  docker-build:
    name: Build ${{matrix.service}}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        service:
          - gateway
          - auth-service
          - employee-service
          - admin-service
          - dashboard-service

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build \
            -t ems-${{ matrix.service }}:${{ github.sha }} \
            ./${{ matrix.service }}

      - name: Verify Image
        run: |
          docker image inspect \
            ems-${{ matrix.service }}:${{ github.sha }}

      - name: List Images
        run: docker images